import { existsSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import type { BotConfig, MarketCategory, RuntimeEnv, TrackedWallet } from "./types.js";

const DEFAULT_ENV: RuntimeEnv = {
  gammaApiUrl: "https://gamma-api.polymarket.com",
  dataApiUrl: "https://data-api.polymarket.com",
  clobApiUrl: "https://clob.polymarket.com",
  clobWsUrl: "wss://ws-subscriptions-clob.polymarket.com/ws/market",
  dbPath: "./data/polymarket-paper-bot.sqlite"
};

export function loadDotEnv(path = ".env"): void {
  if (!existsSync(path)) return;
  const text = readFileSync(path, "utf8");
  for (const line of text.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const index = trimmed.indexOf("=");
    if (index === -1) continue;
    const key = trimmed.slice(0, index).trim();
    const value = trimmed.slice(index + 1).trim().replace(/^['"]|['"]$/g, "");
    if (!(key in process.env)) process.env[key] = value;
  }
}

export function loadRuntimeEnv(): RuntimeEnv {
  loadDotEnv();
  const dbPath = process.env.BOT_DB_PATH || DEFAULT_ENV.dbPath;
  return {
    gammaApiUrl: process.env.GAMMA_API_URL || DEFAULT_ENV.gammaApiUrl,
    dataApiUrl: process.env.DATA_API_URL || DEFAULT_ENV.dataApiUrl,
    clobApiUrl: process.env.CLOB_API_URL || DEFAULT_ENV.clobApiUrl,
    clobWsUrl: process.env.CLOB_WS_URL || DEFAULT_ENV.clobWsUrl,
    dbPath,
    researchTapeDir: process.env.RESEARCH_TAPE_DIR || resolve(dirname(dbPath), "market-tape"),
    cryptoReferenceWsUrl: process.env.CRYPTO_REFERENCE_WS_URL || "wss://data-stream.binance.vision/stream?streams=btcusdt@bookTicker/ethusdt@bookTicker",
    telegramBotToken: process.env.TELEGRAM_BOT_TOKEN || undefined,
    telegramAdminChatId: process.env.TELEGRAM_ADMIN_CHAT_ID || undefined,
    telegramPublicChatId: process.env.TELEGRAM_PUBLIC_CHAT_ID || undefined,
    telegramChatId: process.env.TELEGRAM_CHAT_ID || undefined,
    supabaseUrl: process.env.SUPABASE_URL || undefined,
    supabaseServiceRoleKey: process.env.SUPABASE_SERVICE_ROLE_KEY || undefined,
    supabaseAnonKey: process.env.SUPABASE_ANON_KEY || undefined,
    adminDashboardToken: process.env.ADMIN_DASHBOARD_TOKEN || undefined,
    publicTrackerName: process.env.PUBLIC_TRACKER_NAME || "StratiFi Paper Tracker",
    publicTrackerWalletAddress: process.env.PUBLIC_TRACKER_WALLET_ADDRESS || undefined,
    publicTrackerDisclosure: process.env.PUBLIC_TRACKER_DISCLOSURE || "Paper trading tracker. No live Polymarket orders are placed by this bot."
  };
}

export function loadBotConfig(path = "config/bot.json"): BotConfig {
  const raw = JSON.parse(readFileSync(resolve(path), "utf8")) as BotConfig;
  return {
    ...raw,
    paperMode: true,
    newEntriesEnabled: String(process.env.NEW_ENTRIES_ENABLED ?? raw.newEntriesEnabled ?? "true") !== "false",
    performanceStartAt: Number(process.env.PERFORMANCE_START_AT || (raw.performanceStartAt ?? 0)),
    reserveCashPct: Number(process.env.RESERVE_CASH_PCT || (raw.reserveCashPct ?? 0.2)),
    minSignalConfidence: Number(process.env.MIN_SIGNAL_CONFIDENCE || raw.minSignalConfidence),
    minWalletScore: Number(process.env.MIN_WALLET_SCORE || raw.minWalletScore),
    allowSingleSourceSignals: String(process.env.ALLOW_SINGLE_SOURCE_SIGNALS ?? raw.allowSingleSourceSignals ?? "false") === "true",
    blockedMarketCategories: marketCategoryList(process.env.BLOCKED_MARKET_CATEGORIES, raw.blockedMarketCategories ?? []),
    allowedMarketCategories: marketCategoryList(process.env.ALLOWED_MARKET_CATEGORIES, raw.allowedMarketCategories ?? []),
    categoryTradingGateEnabled: String(process.env.CATEGORY_TRADING_GATE_ENABLED ?? raw.categoryTradingGateEnabled ?? "false") === "true",
    walletLeadTradingEnabled: String(process.env.WALLET_LEAD_TRADING_ENABLED ?? raw.walletLeadTradingEnabled ?? "false") === "true",
    sourceScoringRefreshIntervalMs: Number(process.env.SOURCE_SCORING_REFRESH_INTERVAL_MS || (raw.sourceScoringRefreshIntervalMs ?? 6 * 60 * 60 * 1000)),
    walletResearchEnabled: String(process.env.WALLET_RESEARCH_ENABLED ?? raw.walletResearchEnabled ?? "true") !== "false",
    walletResearchIntervalMs: Number(process.env.WALLET_RESEARCH_INTERVAL_MS || (raw.walletResearchIntervalMs ?? 6 * 60 * 60 * 1000)),
    walletResearchCandidateLimit: Number(process.env.WALLET_RESEARCH_CANDIDATE_LIMIT || (raw.walletResearchCandidateLimit ?? 100)),
    walletResearchTradeLimit: Number(process.env.WALLET_RESEARCH_TRADE_LIMIT || (raw.walletResearchTradeLimit ?? 1000)),
    walletResearchClosedPositionLimit: Number(process.env.WALLET_RESEARCH_CLOSED_POSITION_LIMIT || (raw.walletResearchClosedPositionLimit ?? 200)),
    strategyResearchEnabled: String(process.env.STRATEGY_RESEARCH_ENABLED ?? raw.strategyResearchEnabled ?? "true") !== "false",
    primaryResearchStrategy: process.env.PRIMARY_RESEARCH_STRATEGY as BotConfig["primaryResearchStrategy"] || raw.primaryResearchStrategy || "MACRO_RELEASE",
    weatherStrategyEnabled: String(process.env.WEATHER_STRATEGY_ENABLED ?? raw.weatherStrategyEnabled ?? "true") !== "false",
    weatherMinProbabilityEdge: Number(process.env.WEATHER_MIN_PROBABILITY_EDGE || (raw.weatherMinProbabilityEdge ?? 0.08)),
    weatherMaxProbabilityEdge: Number(process.env.WEATHER_MAX_PROBABILITY_EDGE || (raw.weatherMaxProbabilityEdge ?? 1)),
    weatherAllowedOutcomes: raw.weatherAllowedOutcomes ?? ["YES", "NO"],
    weatherMinEntryPrice: Number(process.env.WEATHER_MIN_ENTRY_PRICE || (raw.weatherMinEntryPrice ?? 0.03)),
    weatherMaxEntryPrice: Number(process.env.WEATHER_MAX_ENTRY_PRICE || (raw.weatherMaxEntryPrice ?? 0.97)),
    weatherMinExpectedValuePct: Number(process.env.WEATHER_MIN_EXPECTED_VALUE_PCT || (raw.weatherMinExpectedValuePct ?? 0.12)),
    weatherMaxUncertainty: Number(process.env.WEATHER_MAX_UNCERTAINTY || (raw.weatherMaxUncertainty ?? 0.35)),
    weatherMinTimeToResolutionHours: Number(process.env.WEATHER_MIN_TIME_TO_RESOLUTION_HOURS || (raw.weatherMinTimeToResolutionHours ?? 2)),
    weatherBacktestDays: Number(process.env.WEATHER_BACKTEST_DAYS || (raw.weatherBacktestDays ?? 21)),
    weatherBacktestIntervalMs: Number(process.env.WEATHER_BACKTEST_INTERVAL_MS || (raw.weatherBacktestIntervalMs ?? 24 * 60 * 60 * 1000)),
    weatherValidationStationLimit: Number(process.env.WEATHER_VALIDATION_STATION_LIMIT || (raw.weatherValidationStationLimit ?? 12)),
    weatherValidationLagDays: Number(process.env.WEATHER_VALIDATION_LAG_DAYS || (raw.weatherValidationLagDays ?? 2)),
    weatherForwardPolicyStartAt: Number(process.env.WEATHER_FORWARD_POLICY_START_AT || (raw.weatherForwardPolicyStartAt ?? 0)),
    weatherForwardPolicyVersion: process.env.WEATHER_FORWARD_POLICY_VERSION || raw.weatherForwardPolicyVersion || "weather-unfrozen",
    weatherForwardMinResolvedTrades: Number(process.env.WEATHER_FORWARD_MIN_RESOLVED_TRADES || (raw.weatherForwardMinResolvedTrades ?? 30)),
    weatherForwardMinReturnPct: Number(process.env.WEATHER_FORWARD_MIN_RETURN_PCT || (raw.weatherForwardMinReturnPct ?? 0.05)),
    weatherTournamentEnabled: String(process.env.WEATHER_TOURNAMENT_ENABLED ?? raw.weatherTournamentEnabled ?? "true") !== "false",
    weatherTournamentPositionSizeUsd: Number(process.env.WEATHER_TOURNAMENT_POSITION_SIZE_USD || (raw.weatherTournamentPositionSizeUsd ?? raw.independentModelFlatPositionSize ?? raw.minPositionSize ?? 10)),
    weatherDedicatedDiscoveryEnabled: String(process.env.WEATHER_DEDICATED_DISCOVERY_ENABLED ?? raw.weatherDedicatedDiscoveryEnabled ?? "true") !== "false",
    weatherDiscoveryEventFetchLimit: Number(process.env.WEATHER_DISCOVERY_EVENT_FETCH_LIMIT || (raw.weatherDiscoveryEventFetchLimit ?? 80)),
    weatherDiscoveryEventSelectLimit: Number(process.env.WEATHER_DISCOVERY_EVENT_SELECT_LIMIT || (raw.weatherDiscoveryEventSelectLimit ?? 12)),
    weatherDiscoveryLookaheadHours: Number(process.env.WEATHER_DISCOVERY_LOOKAHEAD_HOURS || (raw.weatherDiscoveryLookaheadHours ?? 60)),
    weatherExitPolicy: (process.env.WEATHER_EXIT_POLICY || raw.weatherExitPolicy || "GENERIC_MARK_TO_MARKET") as BotConfig["weatherExitPolicy"],
    independentModelMaxOpenTrades: Number(process.env.INDEPENDENT_MODEL_MAX_OPEN_TRADES || (raw.independentModelMaxOpenTrades ?? 4)),
    cryptoThresholdStrategyEnabled: String(process.env.CRYPTO_THRESHOLD_STRATEGY_ENABLED ?? raw.cryptoThresholdStrategyEnabled ?? "true") !== "false",
    cryptoThresholdMinProbabilityEdge: Number(process.env.CRYPTO_THRESHOLD_MIN_PROBABILITY_EDGE || (raw.cryptoThresholdMinProbabilityEdge ?? 0.08)),
    cryptoThresholdMaxProbabilityEdge: Number(process.env.CRYPTO_THRESHOLD_MAX_PROBABILITY_EDGE || (raw.cryptoThresholdMaxProbabilityEdge ?? 0.3)),
    cryptoThresholdMinEntryPrice: Number(process.env.CRYPTO_THRESHOLD_MIN_ENTRY_PRICE || (raw.cryptoThresholdMinEntryPrice ?? 0.2)),
    cryptoThresholdMaxEntryPrice: Number(process.env.CRYPTO_THRESHOLD_MAX_ENTRY_PRICE || (raw.cryptoThresholdMaxEntryPrice ?? 0.8)),
    cryptoThresholdMinTimeToResolutionHours: Number(process.env.CRYPTO_THRESHOLD_MIN_TIME_TO_RESOLUTION_HOURS || (raw.cryptoThresholdMinTimeToResolutionHours ?? 2)),
    cryptoThresholdMaxTimeToResolutionHours: Number(process.env.CRYPTO_THRESHOLD_MAX_TIME_TO_RESOLUTION_HOURS || (raw.cryptoThresholdMaxTimeToResolutionHours ?? 36)),
    cryptoThresholdBacktestIntervalMs: Number(process.env.CRYPTO_THRESHOLD_BACKTEST_INTERVAL_MS || (raw.cryptoThresholdBacktestIntervalMs ?? 24 * 60 * 60 * 1000)),
    cryptoThresholdForwardPolicyStartAt: Number(process.env.CRYPTO_THRESHOLD_FORWARD_POLICY_START_AT || (raw.cryptoThresholdForwardPolicyStartAt ?? 0)),
    cryptoThresholdForwardPolicyVersion: process.env.CRYPTO_THRESHOLD_FORWARD_POLICY_VERSION || raw.cryptoThresholdForwardPolicyVersion || "crypto-unfrozen",
    cryptoThresholdForwardMinResolvedTrades: Number(process.env.CRYPTO_THRESHOLD_FORWARD_MIN_RESOLVED_TRADES || (raw.cryptoThresholdForwardMinResolvedTrades ?? 30)),
    cryptoThresholdForwardMinReturnPct: Number(process.env.CRYPTO_THRESHOLD_FORWARD_MIN_RETURN_PCT || (raw.cryptoThresholdForwardMinReturnPct ?? 0.05)),
    macroCpiStrategyEnabled: String(process.env.MACRO_CPI_STRATEGY_ENABLED ?? raw.macroCpiStrategyEnabled ?? "true") !== "false",
    macroCpiMinProbabilityEdge: Number(process.env.MACRO_CPI_MIN_PROBABILITY_EDGE || (raw.macroCpiMinProbabilityEdge ?? 0.08)),
    macroCpiMaxProbabilityEdge: Number(process.env.MACRO_CPI_MAX_PROBABILITY_EDGE || (raw.macroCpiMaxProbabilityEdge ?? 0.3)),
    macroCpiMinEntryPrice: Number(process.env.MACRO_CPI_MIN_ENTRY_PRICE || (raw.macroCpiMinEntryPrice ?? 0.2)),
    macroCpiMaxEntryPrice: Number(process.env.MACRO_CPI_MAX_ENTRY_PRICE || (raw.macroCpiMaxEntryPrice ?? 0.8)),
    macroCpiMinTimeToReleaseHours: Number(process.env.MACRO_CPI_MIN_TIME_TO_RELEASE_HOURS || (raw.macroCpiMinTimeToReleaseHours ?? 2)),
    macroCpiMaxTimeToReleaseHours: Number(process.env.MACRO_CPI_MAX_TIME_TO_RELEASE_HOURS || (raw.macroCpiMaxTimeToReleaseHours ?? 168)),
    macroCpiBacktestIntervalMs: Number(process.env.MACRO_CPI_BACKTEST_INTERVAL_MS || (raw.macroCpiBacktestIntervalMs ?? 24 * 60 * 60 * 1000)),
    macroCpiForwardPolicyStartAt: Number(process.env.MACRO_CPI_FORWARD_POLICY_START_AT || (raw.macroCpiForwardPolicyStartAt ?? 0)),
    macroCpiForwardPolicyVersion: process.env.MACRO_CPI_FORWARD_POLICY_VERSION || raw.macroCpiForwardPolicyVersion || "macro-cpi-unfrozen",
    macroCpiForwardMinResolvedTrades: Number(process.env.MACRO_CPI_FORWARD_MIN_RESOLVED_TRADES || (raw.macroCpiForwardMinResolvedTrades ?? 30)),
    macroCpiForwardMinReturnPct: Number(process.env.MACRO_CPI_FORWARD_MIN_RETURN_PCT || (raw.macroCpiForwardMinReturnPct ?? 0.05)),
    macroCpiNowcastEnabled: String(process.env.MACRO_CPI_NOWCAST_ENABLED ?? raw.macroCpiNowcastEnabled ?? "true") !== "false",
    macroCpiNowcastUrl: process.env.MACRO_CPI_NOWCAST_URL || raw.macroCpiNowcastUrl || "https://www.clevelandfed.org/indicators-and-data/inflation-nowcasting",
    macroCpiNowcastWeight: Number(process.env.MACRO_CPI_NOWCAST_WEIGHT || (raw.macroCpiNowcastWeight ?? 0.7)),
    macroCpiMaxNowcastAgeMs: Number(process.env.MACRO_CPI_MAX_NOWCAST_AGE_MS || (raw.macroCpiMaxNowcastAgeMs ?? 7 * 24 * 60 * 60_000)),
    independentModelFlatPositionSize: Number(process.env.INDEPENDENT_MODEL_FLAT_POSITION_SIZE || (raw.independentModelFlatPositionSize ?? 0)),
    walletCopyFlatPositionSize: Number(process.env.WALLET_COPY_FLAT_POSITION_SIZE || (raw.walletCopyFlatPositionSize ?? raw.shadowPositionSize)),
    dynamicSizingEnabled: String(process.env.DYNAMIC_SIZING_ENABLED ?? raw.dynamicSizingEnabled ?? "true") !== "false",
    kellyFraction: Number(process.env.KELLY_FRACTION || (raw.kellyFraction ?? 0.25)),
    maxDynamicPositionPct: Number(process.env.MAX_DYNAMIC_POSITION_PCT || (raw.maxDynamicPositionPct ?? 0.05)),
    maxBookDepthPct: Number(process.env.MAX_BOOK_DEPTH_PCT || (raw.maxBookDepthPct ?? 0.1)),
    maxDailyLoss: Number(process.env.MAX_DAILY_LOSS || raw.maxDailyLoss),
    maxLossStreak: Number(process.env.MAX_LOSS_STREAK || raw.maxLossStreak),
    maxTradesPerDay: Number(process.env.MAX_TRADES_PER_DAY || raw.maxTradesPerDay),
    maxPositionSize: Number(process.env.MAX_POSITION_SIZE || raw.maxPositionSize),
    maxOpenExposure: Number(process.env.MAX_OPEN_EXPOSURE || raw.maxOpenExposure),
    signalMarketConcurrency: Number(process.env.SIGNAL_MARKET_CONCURRENCY || (raw.signalMarketConcurrency ?? 6)),
    stopCooldownMs: Number(process.env.STOP_COOLDOWN_MS || (raw.stopCooldownMs ?? 0)),
    marketEntryCooldownMs: Number(process.env.MARKET_ENTRY_COOLDOWN_MS || (raw.marketEntryCooldownMs ?? 0)),
    maxSourceBuyAgeMs: Number(process.env.MAX_SOURCE_BUY_AGE_MS || (raw.maxSourceBuyAgeMs ?? 0)),
    sourceEntryCooldownMs: Number(process.env.SOURCE_ENTRY_COOLDOWN_MS || (raw.sourceEntryCooldownMs ?? 0)),
    shadowCandidateMinScore: Number(process.env.SHADOW_CANDIDATE_MIN_SCORE || (raw.shadowCandidateMinScore ?? 35)),
    liveShadowPolicyVersion: process.env.LIVE_SHADOW_POLICY_VERSION || raw.liveShadowPolicyVersion || "live-shadow-parity-v1",
    forwardObservationMaxLagMs: Number(process.env.FORWARD_OBSERVATION_MAX_LAG_MS || (raw.forwardObservationMaxLagMs ?? raw.maxSourceBuyAgeMs ?? raw.shadowCopyDelayMs)),
    minShadowTradesForPromotion: Number(process.env.MIN_SHADOW_TRADES_FOR_PROMOTION || (raw.minShadowTradesForPromotion ?? 20)),
    minShadowPnlForPromotion: Number(process.env.MIN_SHADOW_PNL_FOR_PROMOTION || (raw.minShadowPnlForPromotion ?? 0)),
    requireShadowProofForDiscovered: String(process.env.REQUIRE_SHADOW_PROOF_FOR_DISCOVERED ?? raw.requireShadowProofForDiscovered ?? "true") !== "false",
    minSellRatioForPromotion: Number(process.env.MIN_SELL_RATIO_FOR_PROMOTION || (raw.minSellRatioForPromotion ?? 0.2)),
    minCategoryConsistencyForPromotion: Number(process.env.MIN_CATEGORY_CONSISTENCY_FOR_PROMOTION || (raw.minCategoryConsistencyForPromotion ?? 55)),
    minCopyabilityForPromotion: Number(process.env.MIN_COPYABILITY_FOR_PROMOTION || (raw.minCopyabilityForPromotion ?? 62)),
    liveParityGateEnabled: String(process.env.LIVE_PARITY_GATE_ENABLED ?? raw.liveParityGateEnabled ?? "false") === "true",
    liveExecutableMinReturnPct: Number(process.env.LIVE_EXECUTABLE_MIN_RETURN_PCT || (raw.liveExecutableMinReturnPct ?? 0.03)),
    minSourceSellRealizedRatio: Number(process.env.MIN_SOURCE_SELL_REALIZED_RATIO || (raw.minSourceSellRealizedRatio ?? 0.35)),
    entryBookDepthMultiple: Number(process.env.ENTRY_BOOK_DEPTH_MULTIPLE || (raw.entryBookDepthMultiple ?? 3)),
    maxEntrySlippage: Number(process.env.MAX_ENTRY_SLIPPAGE || (raw.maxEntrySlippage ?? 0.03)),
    maxExitSlippage: Number(process.env.MAX_EXIT_SLIPPAGE || (raw.maxExitSlippage ?? raw.maxEntrySlippage ?? 0.03)),
    urgentExitSlippage: Number(process.env.URGENT_EXIT_SLIPPAGE || (raw.urgentExitSlippage ?? 0.08)),
    takeProfitExitSlippage: Number(process.env.TAKE_PROFIT_EXIT_SLIPPAGE || (raw.takeProfitExitSlippage ?? raw.maxExitSlippage ?? raw.maxEntrySlippage ?? 0.03)),
    minLiveExecutableShadowTradesForTrading: Number(process.env.MIN_LIVE_EXECUTABLE_SHADOW_TRADES_FOR_TRADING || (raw.minLiveExecutableShadowTradesForTrading ?? 8)),
    minLiveExecutableShadowPnlForTrading: Number(process.env.MIN_LIVE_EXECUTABLE_SHADOW_PNL_FOR_TRADING || (raw.minLiveExecutableShadowPnlForTrading ?? 0)),
    liveExecutableAutoTrackEnabled: String(process.env.LIVE_EXECUTABLE_AUTO_TRACK_ENABLED ?? raw.liveExecutableAutoTrackEnabled ?? "true") !== "false",
    liveExecutableAutoTrackLimit: Number(process.env.LIVE_EXECUTABLE_AUTO_TRACK_LIMIT || (raw.liveExecutableAutoTrackLimit ?? 25)),
    minLiveExecutableShadowWinRateForTrading: Number(process.env.MIN_LIVE_EXECUTABLE_SHADOW_WIN_RATE_FOR_TRADING || (raw.minLiveExecutableShadowWinRateForTrading ?? 0.45)),
    paperProbationTradingEnabled: String(process.env.PAPER_PROBATION_TRADING_ENABLED ?? raw.paperProbationTradingEnabled ?? "false") === "true",
    paperProbationMinSignalConfidence: Number(process.env.PAPER_PROBATION_MIN_SIGNAL_CONFIDENCE || (raw.paperProbationMinSignalConfidence ?? Math.max(raw.minSignalConfidence ?? 0, 78))),
    paperProbationMinWalletScore: Number(process.env.PAPER_PROBATION_MIN_WALLET_SCORE || (raw.paperProbationMinWalletScore ?? Math.max(raw.minWalletScore ?? 0, 72))),
    paperProbationMinCopyabilityScore: Number(process.env.PAPER_PROBATION_MIN_COPYABILITY_SCORE || (raw.paperProbationMinCopyabilityScore ?? Math.max(raw.minCopyabilityForPromotion ?? raw.minWalletScore ?? 0, 70))),
    paperProbationMinSampleConfidence: Number(process.env.PAPER_PROBATION_MIN_SAMPLE_CONFIDENCE || (raw.paperProbationMinSampleConfidence ?? 0.55)),
    paperProbationMinSourceSellRatio: Number(process.env.PAPER_PROBATION_MIN_SOURCE_SELL_RATIO || (raw.paperProbationMinSourceSellRatio ?? Math.min(raw.minSourceSellRealizedRatio ?? 0.35, 0.25))),
    paperProbationEntryDepthMultiple: Number(process.env.PAPER_PROBATION_ENTRY_DEPTH_MULTIPLE || (raw.paperProbationEntryDepthMultiple ?? Math.max(raw.entryBookDepthMultiple ?? 3, 8))),
    paperProbationMaxEntrySlippage: Number(process.env.PAPER_PROBATION_MAX_ENTRY_SLIPPAGE || (raw.paperProbationMaxEntrySlippage ?? raw.maxEntrySlippage ?? 0.02)),
    paperProbationMinRecentTrades: Number(process.env.PAPER_PROBATION_MIN_RECENT_TRADES || (raw.paperProbationMinRecentTrades ?? 1)),
    paperProbationKnownBadLiveExecTrades: Number(process.env.PAPER_PROBATION_KNOWN_BAD_LIVE_EXEC_TRADES || (raw.paperProbationKnownBadLiveExecTrades ?? raw.minLiveExecutableShadowTradesForTrading ?? 3)),
    blockPaperUnderperformers: String(process.env.BLOCK_PAPER_UNDERPERFORMERS ?? raw.blockPaperUnderperformers ?? "true") !== "false",
    minPaperFillsForTrading: Number(process.env.MIN_PAPER_FILLS_FOR_TRADING || (raw.minPaperFillsForTrading ?? 3)),
    minPaperAvgReturnPctForTrading: Number(process.env.MIN_PAPER_AVG_RETURN_PCT_FOR_TRADING || (raw.minPaperAvgReturnPctForTrading ?? -0.02)),
    minPaperPnlForTrading: Number(process.env.MIN_PAPER_PNL_FOR_TRADING || (raw.minPaperPnlForTrading ?? -3)),
    signalDiagnosticsEnabled: String(process.env.SIGNAL_DIAGNOSTICS_ENABLED ?? raw.signalDiagnosticsEnabled ?? "true") !== "false",
    paperExplorationEnabled: String(process.env.PAPER_EXPLORATION_ENABLED ?? raw.paperExplorationEnabled ?? "false") === "true",
    paperExplorationMaxCandidatesPerCycle: Number(process.env.PAPER_EXPLORATION_MAX_CANDIDATES_PER_CYCLE || (raw.paperExplorationMaxCandidatesPerCycle ?? 2)),
    paperExplorationMaxSourceBuyAgeMs: Number(process.env.PAPER_EXPLORATION_MAX_SOURCE_BUY_AGE_MS || (raw.paperExplorationMaxSourceBuyAgeMs ?? raw.maxSourceBuyAgeMs ?? 0)),
    paperExplorationMaxTimeToResolutionHours: Number(process.env.PAPER_EXPLORATION_MAX_TIME_TO_RESOLUTION_HOURS || (raw.paperExplorationMaxTimeToResolutionHours ?? raw.maxTimeToResolutionHours ?? 720)),
    paperExplorationMinConfidence: Number(process.env.PAPER_EXPLORATION_MIN_CONFIDENCE || (raw.paperExplorationMinConfidence ?? raw.minSignalConfidence ?? 75)),
    paperExplorationMinSourceSellRealizedRatio: Number(process.env.PAPER_EXPLORATION_MIN_SOURCE_SELL_REALIZED_RATIO || (raw.paperExplorationMinSourceSellRealizedRatio ?? raw.minSourceSellRealizedRatio ?? 0.35)),
    paperExplorationEntryDepthMultiple: Number(process.env.PAPER_EXPLORATION_ENTRY_DEPTH_MULTIPLE || (raw.paperExplorationEntryDepthMultiple ?? raw.entryBookDepthMultiple ?? 3)),
    parityScorecardIntervalMs: Number(process.env.PARITY_SCORECARD_INTERVAL_MS || (raw.parityScorecardIntervalMs ?? 15 * 60 * 1000)),
    exitRetryCooldownMs: Number(process.env.EXIT_RETRY_COOLDOWN_MS || (raw.exitRetryCooldownMs ?? 5 * 60 * 1000)),
    noBidPositionCloseAfterMs: Number(process.env.NO_BID_POSITION_CLOSE_AFTER_MS || (raw.noBidPositionCloseAfterMs ?? 30 * 60 * 1000)),
    noBookPositionCloseAfterMs: Number(process.env.NO_BOOK_POSITION_CLOSE_AFTER_MS || (raw.noBookPositionCloseAfterMs ?? 2 * 60 * 60 * 1000)),
    sourceExitPollingEnabled: String(process.env.SOURCE_EXIT_POLLING_ENABLED ?? raw.sourceExitPollingEnabled ?? "true") !== "false",
    sourceExitPollIntervalMs: Number(process.env.SOURCE_EXIT_POLL_INTERVAL_MS || (raw.sourceExitPollIntervalMs ?? 30_000)),
    sourceExitWalletTradeLimit: Number(process.env.SOURCE_EXIT_WALLET_TRADE_LIMIT || (raw.sourceExitWalletTradeLimit ?? 80)),
    replayAuditLookbackHours: Number(process.env.REPLAY_AUDIT_LOOKBACK_HOURS || (raw.replayAuditLookbackHours ?? 24)),
    replayAuditWalletLimit: Number(process.env.REPLAY_AUDIT_WALLET_LIMIT || (raw.replayAuditWalletLimit ?? 25)),
    maxTimeToResolutionHours: Number(process.env.MAX_TIME_TO_RESOLUTION_HOURS || (raw.maxTimeToResolutionHours ?? 720)),
    maxPositionHoldHours: Number(process.env.MAX_POSITION_HOLD_HOURS || (raw.maxPositionHoldHours ?? 72)),
    scanIntervalMs: Number(process.env.SCAN_INTERVAL_MS || raw.scanIntervalMs),
    walletActivityLimit: Number(process.env.WALLET_ACTIVITY_LIMIT || raw.walletActivityLimit),
    marketScanLimit: Number(process.env.MARKET_SCAN_LIMIT || raw.marketScanLimit),
    deepHistoryEnabled: String(process.env.DEEP_HISTORY_ENABLED ?? raw.deepHistoryEnabled ?? "true") !== "false",
    deepHistoryWalletLimit: Number(process.env.DEEP_HISTORY_WALLET_LIMIT || (raw.deepHistoryWalletLimit ?? 8)),
    deepHistoryPages: Number(process.env.DEEP_HISTORY_PAGES || (raw.deepHistoryPages ?? 3)),
    deepHistoryPageSize: Number(process.env.DEEP_HISTORY_PAGE_SIZE || (raw.deepHistoryPageSize ?? 100)),
    resolutionBackfillLimit: Number(process.env.RESOLUTION_BACKFILL_LIMIT || (raw.resolutionBackfillLimit ?? 120)),
    executionResearchEnabled: String(process.env.EXECUTION_RESEARCH_ENABLED ?? raw.executionResearchEnabled ?? "true") !== "false",
    makerResearchEnabled: String(process.env.MAKER_RESEARCH_ENABLED ?? raw.makerResearchEnabled ?? "true") !== "false",
    crossMarketResearchEnabled: String(process.env.CROSS_MARKET_RESEARCH_ENABLED ?? raw.crossMarketResearchEnabled ?? "true") !== "false",
    executionResearchUniverseLimit: Number(process.env.EXECUTION_RESEARCH_UNIVERSE_LIMIT || (raw.executionResearchUniverseLimit ?? 120)),
    executionResearchMinVolume24h: Number(process.env.EXECUTION_RESEARCH_MIN_VOLUME_24H || (raw.executionResearchMinVolume24h ?? 1_000)),
    executionResearchBookDepthLevels: Number(process.env.EXECUTION_RESEARCH_BOOK_DEPTH_LEVELS || (raw.executionResearchBookDepthLevels ?? 10)),
    executionResearchPolicyStartAt: Number(process.env.EXECUTION_RESEARCH_POLICY_START_AT || (raw.executionResearchPolicyStartAt ?? 0)),
    executionResearchPolicyVersion: process.env.EXECUTION_RESEARCH_POLICY_VERSION || raw.executionResearchPolicyVersion || "execution-microstructure-unfrozen",
    executionResearchMinResolved: Number(process.env.EXECUTION_RESEARCH_MIN_RESOLVED || (raw.executionResearchMinResolved ?? 200)),
    executionResearchMinDistinctMarkets: Number(process.env.EXECUTION_RESEARCH_MIN_DISTINCT_MARKETS || (raw.executionResearchMinDistinctMarkets ?? 30)),
    executionResearchMinReturnPct: Number(process.env.EXECUTION_RESEARCH_MIN_RETURN_PCT || (raw.executionResearchMinReturnPct ?? 0.02)),
    executionResearchMinWinRate: Number(process.env.EXECUTION_RESEARCH_MIN_WIN_RATE || (raw.executionResearchMinWinRate ?? 0.55)),
    makerResearchQuoteShares: Number(process.env.MAKER_RESEARCH_QUOTE_SHARES || (raw.makerResearchQuoteShares ?? 10)),
    makerResearchPolicyStartAt: Number(process.env.MAKER_RESEARCH_POLICY_START_AT || (raw.makerResearchPolicyStartAt ?? raw.executionResearchPolicyStartAt ?? 0)),
    makerResearchPolicyVersion: process.env.MAKER_RESEARCH_POLICY_VERSION || raw.makerResearchPolicyVersion || raw.executionResearchPolicyVersion || "maker-unfrozen",
    makerResearchMinPairEdge: Number(process.env.MAKER_RESEARCH_MIN_PAIR_EDGE || (raw.makerResearchMinPairEdge ?? 0.01)),
    makerResearchMaxPairEdge: Number(process.env.MAKER_RESEARCH_MAX_PAIR_EDGE || (raw.makerResearchMaxPairEdge ?? 0.08)),
    makerResearchMinQuotePrice: Number(process.env.MAKER_RESEARCH_MIN_QUOTE_PRICE || (raw.makerResearchMinQuotePrice ?? 0.05)),
    makerResearchMaxQuotePrice: Number(process.env.MAKER_RESEARCH_MAX_QUOTE_PRICE || (raw.makerResearchMaxQuotePrice ?? 0.95)),
    makerResearchMaxLegSpread: Number(process.env.MAKER_RESEARCH_MAX_LEG_SPREAD || (raw.makerResearchMaxLegSpread ?? 0.05)),
    makerResearchMaxBookTimestampSkewMs: Number(process.env.MAKER_RESEARCH_MAX_BOOK_TIMESTAMP_SKEW_MS || (raw.makerResearchMaxBookTimestampSkewMs ?? 1_000)),
    makerResearchQuoteTtlMs: Number(process.env.MAKER_RESEARCH_QUOTE_TTL_MS || (raw.makerResearchQuoteTtlMs ?? 30_000)),
    makerResearchMinHedgeDepthMultiple: Number(process.env.MAKER_RESEARCH_MIN_HEDGE_DEPTH_MULTIPLE || (raw.makerResearchMinHedgeDepthMultiple ?? 3)),
    makerResearchMaxHedgeLossPct: Number(process.env.MAKER_RESEARCH_MAX_HEDGE_LOSS_PCT || (raw.makerResearchMaxHedgeLossPct ?? 0.02)),
    makerResearchMaxInventoryShares: Number(process.env.MAKER_RESEARCH_MAX_INVENTORY_SHARES || (raw.makerResearchMaxInventoryShares ?? 20)),
    makerResearchMaxInventoryAgeMs: Number(process.env.MAKER_RESEARCH_MAX_INVENTORY_AGE_MS || (raw.makerResearchMaxInventoryAgeMs ?? 5 * 60_000)),
    makerResearchHedgeRefreshTimeoutMs: Number(process.env.MAKER_RESEARCH_HEDGE_REFRESH_TIMEOUT_MS || (raw.makerResearchHedgeRefreshTimeoutMs ?? 5_000)),
    makerResearchMaxBookAgeMs: Number(process.env.MAKER_RESEARCH_MAX_BOOK_AGE_MS || (raw.makerResearchMaxBookAgeMs ?? 2_000)),
    makerResearchInventorySkewTicks: Number(process.env.MAKER_RESEARCH_INVENTORY_SKEW_TICKS || (raw.makerResearchInventorySkewTicks ?? 1)),
    makerResearchRequoteTicks: Number(process.env.MAKER_RESEARCH_REQUOTE_TICKS || (raw.makerResearchRequoteTicks ?? 2)),
    makerResearchMinTimeToEndMs: Number(process.env.MAKER_RESEARCH_MIN_TIME_TO_END_MS || (raw.makerResearchMinTimeToEndMs ?? 60 * 60_000)),
    pairedResearchShares: Number(process.env.PAIRED_RESEARCH_SHARES || (raw.pairedResearchShares ?? 10)),
    pairedResearchMinNetEdge: Number(process.env.PAIRED_RESEARCH_MIN_NET_EDGE || (raw.pairedResearchMinNetEdge ?? 0.005)),
    binaryArbPolicyStartAt: Number(process.env.BINARY_ARB_POLICY_START_AT || (raw.binaryArbPolicyStartAt ?? raw.executionResearchPolicyStartAt ?? 0)),
    binaryArbPolicyVersion: process.env.BINARY_ARB_POLICY_VERSION || raw.binaryArbPolicyVersion || raw.executionResearchPolicyVersion || "binary-arb-unfrozen",
    binaryArbExecutionLatencyMs: Number(process.env.BINARY_ARB_EXECUTION_LATENCY_MS || (raw.binaryArbExecutionLatencyMs ?? 250)),
    binaryArbExecutionTimeoutMs: Number(process.env.BINARY_ARB_EXECUTION_TIMEOUT_MS || (raw.binaryArbExecutionTimeoutMs ?? 2_000)),
    binaryArbMaxBookAgeMs: Number(process.env.BINARY_ARB_MAX_BOOK_AGE_MS || (raw.binaryArbMaxBookAgeMs ?? 1_000)),
    binaryArbMinDepthMultiple: Number(process.env.BINARY_ARB_MIN_DEPTH_MULTIPLE || (raw.binaryArbMinDepthMultiple ?? 2)),
    thresholdLadderPolicyStartAt: Number(process.env.THRESHOLD_LADDER_POLICY_START_AT || (raw.thresholdLadderPolicyStartAt ?? raw.executionResearchPolicyStartAt ?? 0)),
    thresholdLadderPolicyVersion: process.env.THRESHOLD_LADDER_POLICY_VERSION || raw.thresholdLadderPolicyVersion || raw.executionResearchPolicyVersion || "threshold-ladder-unfrozen",
    thresholdLadderExecutionLatencyMs: Number(process.env.THRESHOLD_LADDER_EXECUTION_LATENCY_MS || (raw.thresholdLadderExecutionLatencyMs ?? 250)),
    thresholdLadderExecutionTimeoutMs: Number(process.env.THRESHOLD_LADDER_EXECUTION_TIMEOUT_MS || (raw.thresholdLadderExecutionTimeoutMs ?? 2_000)),
    thresholdLadderMaxBookAgeMs: Number(process.env.THRESHOLD_LADDER_MAX_BOOK_AGE_MS || (raw.thresholdLadderMaxBookAgeMs ?? 1_000)),
    thresholdLadderMaxBookTimestampSkewMs: Number(process.env.THRESHOLD_LADDER_MAX_BOOK_TIMESTAMP_SKEW_MS || (raw.thresholdLadderMaxBookTimestampSkewMs ?? 500)),
    thresholdLadderMinDepthMultiple: Number(process.env.THRESHOLD_LADDER_MIN_DEPTH_MULTIPLE || (raw.thresholdLadderMinDepthMultiple ?? 2)),
    negRiskArbPolicyStartAt: Number(process.env.NEG_RISK_ARB_POLICY_START_AT || (raw.negRiskArbPolicyStartAt ?? raw.executionResearchPolicyStartAt ?? 0)),
    negRiskArbPolicyVersion: process.env.NEG_RISK_ARB_POLICY_VERSION || raw.negRiskArbPolicyVersion || raw.executionResearchPolicyVersion || "neg-risk-arb-unfrozen",
    crossMarketPolicyStartAt: Number(process.env.CROSS_MARKET_POLICY_START_AT || (raw.crossMarketPolicyStartAt ?? raw.executionResearchPolicyStartAt ?? 0)),
    crossMarketPolicyVersion: process.env.CROSS_MARKET_POLICY_VERSION || raw.crossMarketPolicyVersion || raw.executionResearchPolicyVersion || "cross-market-unfrozen",
    crossMarketResearchSizeUsd: Number(process.env.CROSS_MARKET_RESEARCH_SIZE_USD || (raw.crossMarketResearchSizeUsd ?? 10)),
    crossMarketMoveThresholdBps: Number(process.env.CROSS_MARKET_MOVE_THRESHOLD_BPS || (raw.crossMarketMoveThresholdBps ?? 8)),
    crossMarketMoveWindowMs: Number(process.env.CROSS_MARKET_MOVE_WINDOW_MS || (raw.crossMarketMoveWindowMs ?? 2_000)),
    crossMarketHoldMs: Number(process.env.CROSS_MARKET_HOLD_MS || (raw.crossMarketHoldMs ?? 30_000)),
    crossMarketEntryLatencyMs: Number(process.env.CROSS_MARKET_ENTRY_LATENCY_MS || (raw.crossMarketEntryLatencyMs ?? 250)),
    crossMarketEntryTimeoutMs: Number(process.env.CROSS_MARKET_ENTRY_TIMEOUT_MS || (raw.crossMarketEntryTimeoutMs ?? 2_000)),
    crossMarketMinEntryPrice: Number(process.env.CROSS_MARKET_MIN_ENTRY_PRICE || (raw.crossMarketMinEntryPrice ?? 0.1)),
    crossMarketMaxEntryPrice: Number(process.env.CROSS_MARKET_MAX_ENTRY_PRICE || (raw.crossMarketMaxEntryPrice ?? 0.9)),
    crossMarketMaxSpread: Number(process.env.CROSS_MARKET_MAX_SPREAD || (raw.crossMarketMaxSpread ?? 0.03)),
    crossMarketMinDepthMultiple: Number(process.env.CROSS_MARKET_MIN_DEPTH_MULTIPLE || (raw.crossMarketMinDepthMultiple ?? 3)),
    crossMarketMaxBookAgeMs: Number(process.env.CROSS_MARKET_MAX_BOOK_AGE_MS || (raw.crossMarketMaxBookAgeMs ?? 2_000)),
    crossMarketMaxMarketsPerSignal: Number(process.env.CROSS_MARKET_MAX_MARKETS_PER_SIGNAL || (raw.crossMarketMaxMarketsPerSignal ?? 2)),
    crossMarketSignalCooldownMs: Number(process.env.CROSS_MARKET_SIGNAL_COOLDOWN_MS || (raw.crossMarketSignalCooldownMs ?? 60_000))
  };
}

export function loadTrackedWallets(path = "config/wallets.json"): TrackedWallet[] {
  const wallets = JSON.parse(readFileSync(resolve(path), "utf8")) as TrackedWallet[];
  return wallets
    .filter((wallet) => wallet.enabled)
    .map((wallet) => ({
      ...wallet,
      address: wallet.address.toLowerCase()
    }));
}

function marketCategoryList(value: string | undefined, fallback: MarketCategory[]): MarketCategory[] {
  if (value === undefined) return fallback;
  const valid = new Set<MarketCategory>(["politics", "sports", "crypto", "macro", "company", "culture", "weather", "other"]);
  return [...new Set(value.split(",").map((item) => item.trim().toLowerCase()).filter((item): item is MarketCategory => valid.has(item as MarketCategory)))];
}
